### ISSUE TITLE
Workflow base class not allowed

### ISSUE THREAD

**Issue by JonathanWacks** [carfup/XTBPlugins.DeltaAssemblyvsCrm#14]
In the current implementation, workflows have to derive directly from CodeActivity, otherwise they're not picked up.  However, we are using a base class WorkFlowActivityBase : CodeActivity, and then deriving from that.  The code should check whether a given class has CodeActivity as an ancestor, not necessarily as a direct parent.

**Comment by carfup** [comment]
Hey Jonathan,

Thanks for reaching me regarding this unwanted limitation.
I had this to my to do list for the next release (which would be out soon i hope)

Cheers,
Clément

**Comment by DarylOrwin** [comment]
+1 for this enhancement.  Great tool, good work!

**Comment by carfup** [comment]
Hello guys,

Thanks for the feedback here.
I just published a quick new version to allow the plugin to discover the workflows which doesn't inherit directly from the CodeActivity class.

Version 1.2019.3.21 available from the Plugin Store (#16)

Enjoy,
Clément

**Comment by DarylOrwin** [comment]
Looks good!

**Comment by carfup** [comment]
Closing the issue then. :)
Cheers
