### ISSUE TITLE
Plugin missing in Compare window

### ISSUE THREAD

**Issue by DarylOrwin** [carfup/XTBPlugins.DeltaAssemblyvsCrm#17]
Hi,

I'm comparing 2 assemblies that I know are different.  On the Load screen I can see the missing plugin: 
![image](https://user-images.githubusercontent.com/2320447/54713635-73c9f800-4b25-11e9-85f0-39ba4942695f.png)

But on the compare window I only see the base class:
![image](https://user-images.githubusercontent.com/2320447/54713675-8fcd9980-4b25-11e9-815f-8ef808c5d0f6.png)

Am I missing something or should that highlighted one be on the right side?

**Comment by carfup** [comment]
Sorry, i was too quick for the fix ...
Correcting it now !

**Comment by carfup** [comment]
Fixed : https://www.nuget.org/packages/Carfup.XTBPlugins.DeltaAssemblyvsCrm/1.2019.3.22
It's gonna be available in XrmToolBox after the nuget package sync.

**Comment by DarylOrwin** [comment]
Working now.  Thanks!
